### ISSUE TITLE
setting nickname erases name details in the vcard

### ISSUE THREAD

**Issue by the-reverend** [hnrysmth/ppl#74]
steps to reproduce

```
$ ppl add jdoe 'John Doe'
$ ppl name jdoe 'John Doe' -f Doe -g John -m Henry
$ cat jdoe.vcf 
BEGIN:VCARD
VERSION:3.0
N:Doe;John;Henry;;
FN:John Doe
NICKNAME:
END:VCARD
$ ppl nick jdoe 'Johhny'
$ cat jdoe.vcf 
BEGIN:VCARD
VERSION:3.0
N:;;;;
FN:John Doe
NICKNAME:Johnny
END:VCARD
```

**Comment by the-reverend** [comment]
also, apparently adding a phone number also erases name details.

**Comment by the-reverend** [comment]
```
$ ppl name doe.john -f Doe -g John -m Henry
$ cat doe.john.vcf 
BEGIN:VCARD
VERSION:3.0
N:Doe;John;Henry;;
FN:John Doe
NICKNAME:Johnny
END:VCARD
$ git diff HEAD^
diff --git a/doe.john.vcf b/doe.john.vcf
index 311297d..f617b24 100644
--- a/doe.john.vcf
+++ b/doe.john.vcf
@@ -1,6 +1,6 @@
 BEGIN:VCARD
 VERSION:3.0
-N:;;;;
+N:Doe;John;Henry;;
 FN:John Doe
 NICKNAME:Johnny
 END:VCARD
$ ppl phone doe.john -t home 703.555.1212
$ cat doe.john.vcf 
BEGIN:VCARD
VERSION:3.0
N:;;;;
FN:John Doe
TEL;TYPE=home:703.555.1212
NICKNAME:Johnny
END:VCARD
$ git diff HEAD^
diff --git a/doe.john.vcf b/doe.john.vcf
index f617b24..7b78fda 100644
--- a/doe.john.vcf
+++ b/doe.john.vcf
@@ -1,6 +1,7 @@
 BEGIN:VCARD
 VERSION:3.0
-N:Doe;John;Henry;;
+N:;;;;
 FN:John Doe
+TEL;TYPE=home:703.555.1212
 NICKNAME:Johnny
 END:VCARD
```

**Comment by the-reverend** [comment]
pretty much any action besides `add` and `name` destroys the name information. I'm currently working around this with a shell script:

``` 
#!/bin/bash
set -ueo pipefail
name=`cat ./$2.vcf | grep ^N:`
ppl "$@"
sed -i.bak -E 's/^N:.*/'$name'/' ./$2.vcf
git add -u .
git commit --amend --no-edit
```

this will restore the deleted name information after a change is made. it's kindof ghetto and i give up autocomplete, but it's helping me accomplish my goal.

**Comment by hnrysmth** [comment]
Ouch this was a very silly little mistake! Sorry about the inconvenience this caused. It's fixed now in [3.0.1](https://hnrysmth.github.io/ppl/development/changelog/3.0.1) so hopefully you won't be needing that amazing shell script any more after upgrading to that!! 🤞

Thanks for the detailed bug report and being so patient with me over the xmas period 💜

**Comment by the-reverend** [comment]
no worries! honestly, since this is in deep maintenance mode, and with the holidays, i was ok with a significant delay. i just suck at ruby and it was easier to make lemonade with bash. thanks for the quick fix!

**Comment by the-reverend** [comment]
this is resolved for me. thanks!
